### PR TITLE
introduce a simple http server / browserify watcher for local development

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
I think we should prefer something like [budo](https://github.com/mattdesl/budo) or [watchify-server](https://www.npmjs.com/package/watchify-server).  Thoughts?

**Comment by cvan** [comment]
omg livereload too. I was going to manually add that too. will investigate these options. I like this option better.

**Comment by cvan** [comment]
I just spent more time than I'm willing to admit troubleshooting budo's internals investigating why its filewatcher wasn't working. maybe I'll revisit it later because I like that it ships with LiveReload (or look at its predecessor, [beefy](https://github.com/chrisdickinson/beefy)).

but I like at least using wzrd for simplifying server + browserify stuff. I'm surprised none of these tools have the option of doing an initial compilation when the server/watcher boots up - but whatever.

**Comment by nickdesaulniers** [comment]
nice work, thanks for investigating these servers!

**Pull request merged**
